CREATE TABLE IF NOT EXISTS business_catalog_products (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    business_id BIGINT UNSIGNED NOT NULL,
    catalog_product_id BIGINT UNSIGNED NOT NULL,
    business_sku VARCHAR(120) NULL,
    custom_name_ar VARCHAR(255) NULL,
    custom_name_en VARCHAR(255) NULL,
    price DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    offer_price DECIMAL(12,2) NULL,
    currency_code CHAR(3) NOT NULL DEFAULT 'EGP',
    stock_quantity DECIMAL(12,3) NOT NULL DEFAULT 0.000,
    reserved_quantity DECIMAL(12,3) NOT NULL DEFAULT 0.000,
    stock_status ENUM('in_stock','out_of_stock','limited','preorder') NOT NULL DEFAULT 'in_stock',
    min_order_quantity DECIMAL(12,3) NOT NULL DEFAULT 1.000,
    max_order_quantity DECIMAL(12,3) NULL,
    delivery_time_minutes INT UNSIGNED NULL,
    is_available TINYINT(1) NOT NULL DEFAULT 1,
    is_featured TINYINT(1) NOT NULL DEFAULT 0,
    approval_status ENUM('draft','pending','approved','rejected') NOT NULL DEFAULT 'approved',
    status ENUM('active','inactive','archived') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    meta JSON NULL,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    created_at TIMESTAMP NULL DEFAULT NULL,
    updated_at TIMESTAMP NULL DEFAULT NULL,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY bcp_business_product_unique (business_id, catalog_product_id),
    UNIQUE KEY bcp_business_sku_unique (business_id, business_sku),
    KEY bcp_catalog_product_idx (catalog_product_id),
    KEY bcp_business_status_idx (business_id, status, is_available),
    KEY bcp_stock_idx (stock_status, stock_quantity),
    CONSTRAINT bcp_business_fk FOREIGN KEY (business_id) REFERENCES users(id) ON UPDATE CASCADE,
    CONSTRAINT bcp_catalog_product_fk FOREIGN KEY (catalog_product_id) REFERENCES catalog_products(id) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS business_catalog_product_images (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    business_catalog_product_id BIGINT UNSIGNED NOT NULL,
    image_path VARCHAR(255) NOT NULL,
    image_type ENUM('main','gallery') NOT NULL DEFAULT 'gallery',
    width INT UNSIGNED NULL,
    height INT UNSIGNED NULL,
    size_bytes INT UNSIGNED NULL,
    alt_ar VARCHAR(180) NULL,
    alt_en VARCHAR(180) NULL,
    is_primary TINYINT(1) NOT NULL DEFAULT 0,
    sort_order INT UNSIGNED NOT NULL DEFAULT 0,
    remove_after_sold TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP NULL DEFAULT NULL,
    updated_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id),
    KEY bcpi_product_idx (business_catalog_product_id),
    KEY bcpi_primary_idx (business_catalog_product_id, is_primary),
    CONSTRAINT bcpi_product_fk FOREIGN KEY (business_catalog_product_id) REFERENCES business_catalog_products(id) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
